name: serverCICD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Execute remote commands via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PEM_KEY }}
        port: 22
        script: |
          cd StockForest
          git pull origin main
          cd ~
          docker-compose down
          docker-compose up --build -d
          sudo docker image prune -f

