name: serverCICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./server


    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_ID }}
        DOCKER_PASS: ${{ secrets.DOCKER_PW }}
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Build Docker image
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        IMAGE_NAME=yoon97/stockforest:$TIMESTAMP
        docker build -t $IMAGE_NAME ./server
        echo $IMAGE_NAME > image_name.txt

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=$(cat image_name.txt)
        docker push $IMAGE_NAME

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PEM_KEY }}

    - name: Add SSH known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SSH_PEM_KEY }}
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        IMAGE_NAME=$(cat image_name.txt)
        ssh $EC2_USER@$EC2_HOST << 'EOF'
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
          docker pull $IMAGE_NAME
          docker stop stockforest || true
          docker rm stockforest || true
          docker run -d --name stockforest -p 3000:3000 $IMAGE_NAME
        EOF
