name: serverCICD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Build the project
      run: npm run build --if-present
      working-directory: ./server

    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_ID }}
        DOCKER_PASS: ${{ secrets.DOCKER_PW }}
      run: echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin

    - name: Build Docker image
      id: build-docker # ID를 추가하여 이 단계의 출력을 참조할 수 있게 함
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        IMAGE_NAME=yoon97/stockforest:$TIMESTAMP
        docker build -t $IMAGE_NAME ./server
        echo "::set-output name=image_name::$IMAGE_NAME" # IMAGE_NAME 변수를 출력으로 설정

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME=${{ steps.build-docker.outputs.image_name }} # 이전 단계의 출력 참조
        docker push $IMAGE_NAME

    - name: Execute remote commands via SSH
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PEM_KEY }}
        port: 22
        envs: IMAGE_NAME=${{ steps.build-docker.outputs.image_name }} # IMAGE_NAME 변수를 환경 변수로 전달
        script: |
          echo "Pulling Docker image: $IMAGE_NAME"
          docker pull $IMAGE_NAME # 환경 변수에서 IMAGE_NAME을 사용
          docker stop stockforest || true
          docker rm stockforest || true
          docker run -d --name stockforest -p 3000:3000 $IMAGE_NAME # 환경 변수에서 IMAGE_NAME을 사용
